version: '3.8'
networks:
  app_net:
    driver: bridge
services:
  server:
    container_name: server
    hostname: server
    restart: always
    build: ./server/
    ports:
      - "8080:8080"
    networks:
      - app_net
  mongodb:
    container_name: mongodb
    hostname: mongodb
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/database:/data/db
    networks:
      - app_net
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongodb
    networks:
      - app_net
    ports:
      - "3000:3000"
  proxy:
    image: nginx:latest
    container_name: proxy
    hostname: proxy
    depends_on:
      - server
      - mongoclient
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9000:80"
    networks:
      - app_net


